auctions/urls.py
from django.urls import path

from . import views
app_name="auctions"
urlpatterns = [
    path("", views.index, name="index"),
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("register/", views.register, name="register"),
    path("categories/", views.categories, name="categories"),
    path("category/<str:category>", views.category, name="category"),
    path("create/", views.create, name="create"),
    path("submit/",views.submit,name="submit"),
    path("listings/<int:id>",views.listingpage,name="listingpage"),
    path("bidsubmit/<int:listingid>",views.bidsubmit,name="bidsubmit"),
    path("cmntsubmit/<int:listingid>",views.cmntsubmit,name="cmntsubmit"),
    path("addwatchlist/<int:listingid>",views.addwatchlist,name="addwatchlist"),
    path("removewatchlist/<int:listingid>",views.removewatchlist,name="removewatchlist"),
    path("watchlist/<str:username>",views.watchlist,name="watchlist"),
    path("closebid/<int:listingid>",views.closebid,name="closebid"),
    path("winnings/",views.winnings,name="winnings")
]

commerce/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls"))
]

auctions/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    pass
class Listing(models.Model):
    owner = models.CharField(max_length=64)
    title = models.CharField(max_length=64)
    description = models.TextField()
    price = models.IntegerField()
    category = models.CharField(max_length=64)
    link = models.CharField(max_length=64,default=None,blank=True,null=True)
    time = models.CharField(max_length=64)

class Bid(models.Model):
    user = models.CharField(max_length=64)
    title = models.CharField(max_length=64)
    listingid = models.IntegerField()
    bid = models.IntegerField()

class Comment(models.Model):
    user = models.CharField(max_length=64)
    time = models.CharField(max_length=64)
    comment = models.TextField()
    listingid = models.IntegerField()

class Watchlist(models.Model):
    user = models.CharField(max_length=64)
    listingid = models.IntegerField()

class Closedbid(models.Model):
    owner = models.CharField(max_length=64)
    winner = models.CharField(max_length=64)
    listingid = models.IntegerField()
    winprice = models.IntegerField()

class Alllisting(models.Model):
    listingid = models.IntegerField()
    title = models.CharField(max_length=64)
    description = models.TextField()
    link = models.CharField(max_length=64,default=None,blank=True,null=True)

auctions/views.py
from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from .models import User,Bid,Listing,Comment,Watchlist,Closedbid,Alllisting
from datetime import datetime




def index(request):
    items=Listing.objects.all()
    try:
        w = Watchlist.objects.filter(user=request.user.username)
        wcount=len(w)
    except:
        wcount=None
    return render(request, "auctions/index.html",{
        "items":items,
        "wcount":wcount
    })

def categories(request):
    items=Listing.objects.raw("SELECT * FROM auctions_listing GROUP BY category")
    try:
        w = Watchlist.objects.filter(user=request.user.username)
        wcount=len(w)
    except:
        wcount=None
    return render(request,"auctions/categorypage.html",{
        "items": items,
        "wcount":wcount
    })

def category(request,category):
    catitems = Listing.objects.filter(category=category)
    try:
        w = Watchlist.objects.filter(user=request.user.username)
        wcount=len(w)
    except:
        wcount=None
    return render(request,"auctions/category.html",{
        "items":catitems,
        "cat":category,
        "wcount":wcount
    })

def create(request):
    try:
        w = Watchlist.objects.filter(user=request.user.username)
        wcount=len(w)
    except:
        wcount=None
    return render(request,"auctions/create.html",{
        "wcount":wcount
    })

def submit(request):
    if request.method == "POST":
        listtable = Listing()
        now = datetime.now()
        dt = now.strftime(" %d %B %Y %X ")
        listtable.owner = request.user.username
        listtable.title = request.POST.get('title')
        listtable.description = request.POST.get('description')
        listtable.price = request.POST.get('price')
        listtable.category = request.POST.get('category')
        if request.POST.get('link'):
            listtable.link = request.POST.get('link')
        else :
            listtable.link = "https://previews.123rf.com/images/eatcute/eatcute1411/eatcute141112107/34109553-shopping-flat-app-ui-background-eps10.jpg"
        listtable.time = dt
        listtable.save()
        all = Alllisting()
        items = Listing.objects.all()
        for i in items:
            try:
                if Alllisting.objects.get(listingid=i.id):
                    pass
            except:
                all.listingid=i.id
                all.title = i.title
                all.description = i.description
                all.link = i.link
                all.save()

        return redirect('auctions:index')
    else:
        return redirect('auctions:index')


def listingpage(request,id):
    try:
        item = Listing.objects.get(id=id)
    except:
        return redirect('auctions:index')
    try:
        comments = Comment.objects.filter(listingid=id)
    except:
        comments = None
    if request.user.username:
        try:
            if Watchlist.objects.get(user=request.user.username,listingid=id):
                added=True
        except:
            added = False
        try:
            l = Listing.objects.get(id=id)
            if l.owner == request.user.username :
                owner=True
            else:
                owner=False
        except:
            return redirect('auctions:index')
    else:
        added=False
        owner=False
    try:
        w = Watchlist.objects.filter(user=request.user.username)
        wcount=len(w)
    except:
        wcount=None
    return render(request,"auctions/listingpage.html",{
        "i":item,
        "error":request.COOKIES.get('error'),
        "errorgreen":request.COOKIES.get('errorgreen'),
        "comments":comments,
        "added":added,
        "owner":owner,
        "wcount":wcount
    })

def bidsubmit(request,listingid):
    current_bid = Listing.objects.get(id=listingid)
    current_bid=current_bid.price
    if request.method == "POST":
        user_bid = int(request.POST.get("bid"))
        if user_bid > current_bid:
            listing_items = Listing.objects.get(id=listingid)
            listing_items.price = user_bid
            listing_items.save()
            try:
                if Bid.objects.filter(id=listingid):
                    bidrow = Bid.objects.filter(id=listingid)
                    bidrow.delete()
                bidtable = Bid()
                bidtable.user=request.user.username
                bidtable.title = listing_items.title
                bidtable.listingid = listingid
                bidtable.bid = user_bid
                bidtable.save()
                
            except:
                bidtable = Bid()
                bidtable.user=request.user.username
                bidtable.title = listing_items.title
                bidtable.listingid = listingid
                bidtable.bid = user_bid
                bidtable.save()
            response = redirect('auctions:listingpage',id=listingid)
            response.set_cookie('errorgreen','bid successful!!!',max_age=3)
            return response
        else :
            response = redirect('auctions:listingpage',id=listingid)
            response.set_cookie('error','Bid should be greater than current price',max_age=3)
            return response
    else:
        return redirect('auctions:index')


def cmntsubmit(request,listingid):
    if request.method == "POST":
        now = datetime.now()
        dt = now.strftime(" %d %B %Y %X ")
        c = Comment()
        c.comment = request.POST.get('comment')
        c.user = request.user.username
        c.time = dt
        c.listingid = listingid
        c.save()
        return redirect('auctions:listingpage',id=listingid)
    else :
        return redirect('auctions:index')

def addwatchlist(request,listingid):
    if request.user.username:
        w = Watchlist()
        w.user = request.user.username
        w.listingid = listingid
        w.save()
        return redirect('auctions:listingpage',id=listingid)
    else:
        return redirect('auctions:index')


def removewatchlist(request,listingid):
    if request.user.username:
        try:
            w = Watchlist.objects.get(user=request.user.username,listingid=listingid)
            w.delete()
            return redirect('auctions:listingpage',id=listingid)
        except:
            return redirect('auctions:listingpage',id=listingid)
    else:
        return redirect('auctions:index')

def watchlist(request,username):
    if request.user.username:
        try:
            w = Watchlist.objects.filter(user=username)
            items = []
            for i in w:
                items.append(Listing.objects.filter(id=i.listingid))
            try:
                w = Watchlist.objects.filter(user=request.user.username)
                wcount=len(w)
            except:
                wcount=None
            return render(request,"auctions/watchlist.html",{
                "items":items,
                "wcount":wcount
            })
        except:
            try:
                w = Watchlist.objects.filter(user=request.user.username)
                wcount=len(w)
            except:
                wcount=None
            return render(request,"auctions/watchlist.html",{
                "items":None,
                "wcount":wcount
            })
    else:
        return redirect('auctions:index')

def closebid(request,listingid):
    if request.user.username:
        try:
            listingrow = Listing.objects.get(id=listingid)
        except:
            return redirect('auctions:index')
        cb = Closedbid()
        title = listingrow.title
        cb.owner = listingrow.owner
        cb.listingid = listingid
        try:
            bidrow = Bid.objects.get(listingid=listingid,bid=listingrow.price)
            cb.winner = bidrow.user
            cb.winprice = bidrow.bid
            cb.save()
            bidrow.delete()
        except:
            cb.winner = listingrow.owner
            cb.winprice = listingrow.price
            cb.save()
        try:
            if Watchlist.objects.filter(listingid=listingid):
                watchrow = Watchlist.objects.filter(listingid=listingid)
                watchrow.delete()
            else:
                pass
        except:
            pass
        try:
            crow = Comment.objects.filter(listingid=listingid)
            crow.delete()
        except:
            pass
        try:
            brow = Bid.objects.filter(listingid=listingid)
            brow.delete()
        except:
            pass
        try:
            cblist=Closedbid.objects.get(listingid=listingid)
        except:
            cb.owner = listingrow.owner
            cb.winner = listingrow.owner
            cb.listingid = listingid
            cb.winprice = listingrow.price
            cb.save()
            cblist=Closedbid.objects.get(listingid=listingid)
        listingrow.delete()
        try:
            w = Watchlist.objects.filter(user=request.user.username)
            wcount=len(w)
        except:
            wcount=None
        return render(request,"auctions/winningpage.html",{
            "cb":cblist,
            "title":title,
            "wcount":wcount
        })   

    else:
        return redirect('auctions:index')     

def winnings(request):
    if request.user.username:
        items=[]
        try:
            wonitems = Closedbid.objects.filter(winner=request.user.username)
            for w in wonitems:
                items.append(Alllisting.objects.filter(listingid=w.listingid))
        except:
            wonitems = None
            items = None
        try:
            w = Watchlist.objects.filter(user=request.user.username)
            wcount=len(w)
        except:
            wcount=None

auctions/templates/auctions/category.html
{% extends "auctions/layout.html" %}

{% block body %}
 <div class="container">
    <h2>Category:{{cat}}</h2>

 </div>
 <div class="container" id="listings">
    {% for i in items %}
    <div class="card mb-3" style="max-width: 540px;" id="card-listings">
        <div class="row no-gutters">
          <div class="col-md-4">
            <img src="{{i.link}}" class="card-img" alt="...">
          </div>
          <div class="col-md-8">
            <div class="card-body">
              <h5 class="card-title">{{i.title}}</h5>
              <p class="card-text">{{i.description}}</p>
              <p class="card-text">${{i.price}}</p>
              <a href="{% url 'auctions:listingpage' id=i.id %}"><button class="btn btn-outline-info">Bid Now!</button></a>
              <p class="card-text"><small class="text-muted">{{i.time}}</small></p>
            </div>
          </div>
        </div>
      </div>
      {% endfor %}
 </div>
{% endblock %}

auctions/templates/auctions/categorypage.html
{% extends "auctions/layout.html" %}
{% block body %}
<div class="container">
    <h2>Categories</h2>

</div>
<div class="container">
    <ul>
        {% for i in items %}
        <li>
            <a href="{% url 'auctions:category' category=i.category %}">{{i.category}}</a>
            </li>
        {% endfor %}
    </ul>
    

</div>
{% endblock %}

auctions/templates/auctions/categpage.html
{% extends "auctions/layout.html" %}
{% block body %}
<div class="container">
    <h2>Categories</h2>

</div>
<div class="container">
    <ul>
        {% for i in items %}
        <li>
            <a href="{% url 'auctions:category' category=i.category %}">{{i.category}}</a>
            </li>
        {% endfor %}
    </ul>
    

</div>
{% endblock %}

auctions/templates/auctions/create.html
{% extends "auctions/layout.html" %}
{% block body %}
 <div class="container">
    <h2>Create listing</h2>

 </div>
 <div class="container">
    <form action="{% url 'auctions:submit' %}" method="POST">
        {% csrf_token %}
        <div class="form-group">
          <label for="exampleFormControlInput1">Title</label>
          <input type="text" class="form-control" id="exampleFormControlInput1" placeholder="Title of the lisiting..." name="title" required>
        </div>
        
        <div class="form-group">
          <label for="exampleFormControlTextarea1">Description</label>
          <textarea class="form-control" id="exampleFormControlTextarea1" rows="5" placeholder="Description..." name="description" required></textarea>
        </div>
          <div class="form-group">
            <label for="exampleFormControlSelect1">Category</label>
            <select class="form-control" id="exampleFormControlSelect1" name="category" required>
              <option>Fashion</option>
              <option>Tools</option>
              <option>Toys</option>
              <option>Electronics</option>
              <option>Home accessories</option>
              <option>Books</option>
            </select>
          </div>
        <div class="form-group">
            <label for="exampleFormControlInput1">Initial Bid</label>
            <input type="number" class="form-control" id="exampleFormControlInput1" placeholder="Starting bid..." name="price" required>
          </div>
        
          <div class="form-group">
            <label for="exampleFormControlInput1">Image link (optional)</label>
            <input type="text" class="form-control" id="exampleFormControlInput1" placeholder="copy the link...." name="link">
          </div>

        <button class="btn btn-outline-info" type="submit">Submit</button>

      </form>
 </div>
{% endblock %}

auctions/templates/auctions/index.html
{% extends "auctions/layout.html" %}

{% block body %}
<div class="container">
    <h2>Active Listings</h2>

</div>
<div class="container" id="listings">
    {% for i in items %}
    <div class="card mb-3" style="max-width: 540px;" id="card-listings">
        <div class="row no-gutters">
          <div class="col-md-4">
            <img src="{{i.link}}" class="card-img" alt="...">
          </div>
          <div class="col-md-8">
            <div class="card-body">
              <h5 class="card-title">{{i.title}}</h5>
              <p class="card-text">{{i.description}}</p>
              <p class="card-text">${{i.price}}</p>
              <a href="{% url 'auctions:listingpage' id=i.id %}"><button class="btn btn-outline-info">Bid Now!</button></a>
              <p class="card-text"><small class="text-muted">{{i.time}}</small></p>
            </div>
          </div>
        </div>
      </div>
      {% endfor %}
</div>
{% endblock %}

auctions/templates/auctions/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}Auctions{% endblock %}</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'auctions/style.css' %}">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <a class="navbar-brand mb-0 h1" href="#">Auctions</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
          
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'auctions:index' %}">Active Listings <span class="sr-only">(current)</span></a>
                </li>
                {% if user.is_authenticated %}
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'auctions:categories' %}">Categories</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'auctions:watchlist' username=user.username %}">Watchlist <span class="badge badge-light">{{wcount}}</span></a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'auctions:create' %}">Create Listing</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'auctions:winnings' %}">Your Winnings</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'auctions:logout' %}">Logout</a>
                  </li>
                {% else %}
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'auctions:login' %}">Login</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'auctions:register' %}">Register</a>
                  </li>
                {% endif %}
              </ul>
              <div class="form-inline my-2 my-lg-0 text-light">
                {% if user.is_authenticated %}
                  Signed in as &nbsp;<strong>{{ user.username }}</strong>
                {% else %}
                  Not signed in
                {% endif %}
              </div>
            </div>
          </nav>
        <hr>
        {% block body %}
        {% endblock %}
    </body>
</html>

auctions/templates/auctions/listingpage.html
{% extends "auctions/layout.html" %}
{% block body %}
 <div class="container">
    <h2>Listing:{{i.title}}</h2>
    <div class="container" style="text-align: center;">
        <img src="{{i.link}}" width="30%" alt="...">
    </div>
    <br>
    <p><b>Description:</b>{{i.description}}</p>
    <br>
    {% if user.username %}
    <p>
      {% if added %}
      <a href="{% url 'auctions:removewatchlist' listingid=i.id %}"><button class="btn btn-danger">Remove from watchlist</button></a>
      {% else %}
      <a href="{% url 'auctions:addwatchlist' listingid=i.id %}"><button class="btn btn-success">Add to watchlist</button></a>
      {% endif %}
    </p>
    <br>
    {% endif %}
    <h3>Current Bid:${{i.price}}</h3>
    {% if user.username %}
    {% if owner %}
    <br>
    <a href="{% url 'auctions:closebid' listingid=i.id %}"><button class="btn btn-warning">Close Bid</button></a>
    <br>
    {% endif %}
    {% endif %}
    <br>
    <p><b>Details:</b>
    <ul>
        <li><b>Owner:</b>{{i.owner}}</li>
        <li><b>Category:</b>{{i.category}}</li>
        <li><b>Created on:</b>{{i.time}}</li>
    </ul>
    </p>
    {% if error %}
    <div class="alert alert-danger" role="alert">
        {{error}}
      </div>
    {% endif %}
    {% if errorgreen %}
    <div class="alert alert-success" role="alert">
        {{errorgreen}}
      </div>
    {% endif %}
    {% if user.username %}
    <div class="container">
        <h4>Place your bid:</h4>
        <form action="{% url 'auctions:bidsubmit' listingid=i.id %}" method="POST">
            {% csrf_token %}
              <div class="form-row align-items-center">
                <div class="col-auto">
                  <input type="number" class="form-control mb-2" id="inlineFormInput" name="bid" placeholder="your bid...">
                </div>
                <div class="col-auto">
                  <button type="submit" class="btn btn-primary mb-2">Submit</button>
                </div>
              </div>
        </form>

    </div>
    <br>
    <div class="container">
      <form action="{% url 'auctions:cmntsubmit' listingid=i.id %}" method="POST">
        {% csrf_token %}
        <div class="form-group">
          <label for="exampleFormControlTextarea1"><b>Write a comment:</b></label>
          <textarea class="form-control" id="exampleFormControlTextarea1" rows="3" name="comment" placeholder="Write your comment here..." required></textarea>
        </div>
        <button class="btn btn-secondary" type="submit">Submit</button>
      </form>
    </div>
    <br>
    {% endif %}
    {% if comments %}
    <h3>Comments:</h3>
    <div class="container">
          
          {% for c in comments %}
          <div class="card mb-3" style="max-width: 540px;">
            <div class="row no-gutters">
              <div class="col-md-8">
                <div class="card-body">
                  <h5 class="card-title">{{c.user}}</h5>
                  <p class="card-text">{{c.comment}}</p>
                  <p class="card-text"><small class="text-muted">{{c.time}} UTC</small></p>
                </div>
              </div>
            </div>
          </div>
           {% endfor %}
           
    </div>
    {% endif %}
 </div>




{% endblock %}

auctions/templates/auctions/login.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Login</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'auctions:login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form>

    Don't have an account? <a href="{% url 'auctions:register' %}">Register here.</a>

{% endblock %}

auctions/templates/auctions/mywinnings.html
{% extends "auctions/layout.html" %}

{% block body %}
 <div class="container">
    <h2>Your Winnings</h2>
 </div>

 <div class="container" id="listings">
    {% for item in items %}
    {% for i in item %}
    <div class="card mb-3" style="max-width: 540px;" id="card-listings">
        <div class="row no-gutters">
          <div class="col-md-4">
            <img src="{{i.link}}" class="card-img" alt="...">
          </div>
          <div class="col-md-8">
            <div class="card-body">
              <h5 class="card-title">{{i.title}}</h5>
              <p class="card-text">{{i.description}}</p>
              {% for j in wonitems %}
              {% if i.listingid == j.listingid %}
              <p class="card-text"><b>Winning Bid:</b>${{j.winprice}}</p>
              <p class="card-text"><b>Owner:</b>{{j.owner}}</p>
              {% endif %}
              {% endfor %}
            </div>
          </div>
        </div>
      </div>
      
      {% endfor %}
      {% endfor %}
  </div>
{% endblock %}

auctions/templates/auctions/register.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Register</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'auctions:register' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Register">
    </form>

    Already have an account? <a href="{% url 'auctions:login' %}">Log In here.</a>

{% endblock %}

auctions/templates/auctions/watchlist.html
{% extends "auctions/layout.html" %}

{% block body %}
 <div class="container">
    <h2>Watchlist</h2>
  
 </div>
 <div class="container" id="listings">
    {% for item in items %}
    {% for i in item %}
    <div class="card mb-3" style="max-width: 540px;" id="card-listings">
        <div class="row no-gutters">
          <div class="col-md-4">
            <img src="{{i.link}}" class="card-img" alt="...">
          </div>
          <div class="col-md-8">
            <div class="card-body">
              <h5 class="card-title">{{i.title}}</h5>
              <p class="card-text">{{i.description}}</p>
              <p class="card-text">${{i.price}}</p>
              <a href="{% url 'auctions:listingpage' id=i.id %}"><button class="btn btn-outline-success">Bid Now!</button></a>
              <p class="card-text"><small class="text-muted">{{i.time}}</small></p>
            </div>
          </div>
        </div>
      </div>
      {% endfor %}
      {% empty %}
       <li>No Listings found.....</li>
      {% endfor %}
  </div>
{% endblock %}

auctions/templates/auctions/watchlistpage.html
{% extends "auctions/layout.html" %}

{% block body %}
 <div class="container">
    <h2>Watchlist</h2>
  
 </div>
 <div class="container" id="listings">
    {% for item in items %}
    {% for i in item %}
    <div class="card mb-3" style="max-width: 540px;" id="card-listings">
        <div class="row no-gutters">
          <div class="col-md-4">
            <img src="{{i.link}}" class="card-img" alt="...">
          </div>
          <div class="col-md-8">
            <div class="card-body">
              <h5 class="card-title">{{i.title}}</h5>
              <p class="card-text">{{i.description}}</p>
              <p class="card-text">${{i.price}}</p>
              <a href="{% url 'auctions:listingpage' id=i.id %}"><button class="btn btn-outline-success">Bid Now!</button></a>
              <p class="card-text"><small class="text-muted">{{i.time}}</small></p>
            </div>
          </div>
        </div>
      </div>
      {% endfor %}
      {% empty %}
      <h3>No listings found in your watchlist...</h3>
      {% endfor %}
  </div>
{% endblock %}

auctions/templates/auctions/winningpage.html
{% extends "auctions/layout.html" %}

{% block body %}
 <div class="container">
    <h2>{{title}}</h2>
 </div>
 <div class="container" id="listings">
    <h3>This listing is no longer active.</h3>
    {% if cb.winner == user.username %}
      <h6 style="color: red;">The item is not sold to others.</h6>
      <p style="color: green;">You won this bid.</p>
    {% endif %}
    <ul>
        <li><b>Owner:</b>{{cb.owner}}</li>
        <li><b>Winner:</b>{{cb.winner}}</li>
        <li><b>Winning Price:</b>{{cb.winprice}}</li>
    </ul>
 </div>
{% endblock %}

auctions/templates/auctions/winnings.html
{% extends "auctions/layout.html" %}

{% block body %}
 <div class="container">
    <h2>Your Winnings</h2>
 </div>

 <div class="container" id="listings">
    {% for item in items %}
    {% for i in item %}
    <div class="card mb-3" style="max-width: 540px;" id="card-listings">
        <div class="row no-gutters">
          <div class="col-md-4">
            <img src="{{i.link}}" class="card-img" alt="...">
          </div>
          <div class="col-md-8">
            <div class="card-body">
              <h5 class="card-title">{{i.title}}</h5>
              <p class="card-text">{{i.description}}</p>
              {% for j in wonitems %}
              {% if i.listingid == j.listingid %}
              <p class="card-text"><b>Winning Bid:</b>${{j.winprice}}</p>
              <p class="card-text"><b>Owner:</b>{{j.owner}}</p>
              {% endif %}
              {% endfor %}
            </div>
          </div>
        </div>
      </div>
      
      {% endfor %}
      {% empty %}
        <li>No winnings yet...</li>
      {% endfor %}
  </div>
{% endblock %}